[package]
name = "brachiologo"
version = "0.1.0"
authors = ["Joe Neeman <joeneeman@gmail.com>"]
edition = "2021"
description = "Parser and evaluator for the LOGO language"
readme = "README.md"

[dependencies]
nom = "7.1.2"
